services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      # (opcional) passe um build-arg para bust de cache quando mexer no CSS:
      # args:
      #   - THEME_SHA=${THEME_SHA:-dev}
    restart: always
    ports:
      - "3080:3080"
    volumes:
      # seu .env do APP (contém MONGO_URI, MEILI_HOST, RAG_API_URL, etc.)
      - type: bind
        source: ./.env
        target: /app/.env
      # sua config do app
      - type: bind
        source: ./custom/librechat.yaml
        target: /app/config/librechat.yaml
      # estáticos/persistências opcionais
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    # se seus serviços externos só são resolvidos por host.docker.internal:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # se você usa nomes de serviço via rede externa compartilhada:
    # networks:
    #   default:
    #     external: true
    #     name: sua_rede_compartilhada
