services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3080:3080"   # ajuste se 3080 já estiver ocupado
    # NÃO repita aqui MONGO_URI/MEILI_HOST/etc. Se estão no .env do app, já basta.
    volumes:
      # 1) .env do APLICATIVO dentro do container (LibreChat lê /app/.env)
      - type: bind
        source: ./.env
        target: /app/.env

      # 2) sua config do LibreChat (hot-swap sem rebuild)
      - type: bind
        source: ./custom/librechat.yaml
        target: /app/config/librechat.yaml

      # 3) estáticos/persistências opcionais
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs

    # (Opcional) Se seus outros serviços estão em outra rede Docker e você usa nomes de serviço,
    # adicione a mesma rede externa aqui:
    # networks:
    #   default:
    #     external: true
    #     name: sua_rede_compartilhada
